package gui;

//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import agents.UserAgent;
import gui.oyentes.OyenteBoton;
import gui.oyentes.OyenteMenu;
import agents.UserAgent;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import javax.swing.JComboBox;

@SuppressWarnings({ "serial", "unused" })
public class UserGUI extends JFrame {
	
	UserAgent userAgent;
	
	JPanel panel0;
	JButton but0;
	JTextArea area0;
	@SuppressWarnings("rawtypes")
	JComboBox combo0;
	JPanel panel1;
	JLabel image;

	@SuppressWarnings({ "rawtypes", "unchecked", "unused" })
	public UserGUI() {

		super("Agente Usuario");
		
		// Barra de Menu
        JMenuBar menuBar = new JMenuBar();
        this.setJMenuBar(menuBar);

        JMenu archivo = new JMenu("Archivo");
        JMenu ayuda = new JMenu("Ayuda");

        JMenuItem salir = new JMenuItem("Salir");
        JMenuItem ver_ayuda = new JMenuItem("Ver ayuda");
        JMenuItem info = new JMenuItem("Acerca de nosotros");

        salir.setActionCommand("Salir");
        salir.addActionListener(new OyenteMenu());

        ver_ayuda.setActionCommand("Ayuda");
        ver_ayuda.addActionListener(new OyenteMenu());

        info.setActionCommand("Info");
        info.addActionListener(new OyenteMenu());

        menuBar.add(archivo);
        menuBar.add(ayuda);

        archivo.add(salir);

        ayuda.add(ver_ayuda);
        ayuda.add(info);

        
        //Implementación de la GUI
		panel0 = new JPanel();
		GridBagLayout gbpanel0 = new GridBagLayout();
		GridBagConstraints gbcpanel0 = new GridBagConstraints();
		panel0.setLayout(gbpanel0);
		panel0.setBorder(BorderFactory.createEmptyBorder(15,15,15,15));

		String[] datacombo0 = {"Chocolate","Ice Cream","Apple Pie"};
		combo0 = new JComboBox(datacombo0);
		gbcpanel0.gridx = 2;
		gbcpanel0.gridy = 1;
		gbcpanel0.gridwidth = 15;
		gbcpanel0.gridheight = 2;
		gbcpanel0.fill = GridBagConstraints.BOTH;
		gbcpanel0.weightx = 1;
		gbcpanel0.weighty = 0;
		gbcpanel0.anchor = GridBagConstraints.NORTH;
		gbpanel0.setConstraints(combo0, gbcpanel0);
		panel0.add(combo0);
		
		but0 = new JButton("Solicitar un cupo");
		but0.setActionCommand("Reservar viaje");
		but0.addActionListener(new OyenteBoton(combo0.getSelectedIndex()));
		gbcpanel0.gridx = 18;
		gbcpanel0.gridy = 1;
		gbcpanel0.gridwidth = 1;
		gbcpanel0.gridheight = 2;
		//gbcpanel0.fill = GridBagConstraints.BOTH;
		gbcpanel0.weightx = 1;
		gbcpanel0.weighty = 0;
		gbcpanel0.anchor = GridBagConstraints.NORTH;
		gbpanel0.setConstraints(but0, gbcpanel0);
		panel0.add(but0);

		area0 = new JTextArea(4, 10);
		area0.setLineWrap(true);
		area0.setWrapStyleWord(true);
		area0.setBorder(BorderFactory.createEmptyBorder(15,15,15,15));
		JScrollPane scparea0 = new JScrollPane(area0);
		scparea0.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
		gbcpanel0.gridx = 1;
		gbcpanel0.gridy = 23;
		gbcpanel0.gridwidth = 18;
		gbcpanel0.gridheight = 1;
		gbcpanel0.fill = GridBagConstraints.BOTH;
		gbcpanel0.weightx = 1;
		gbcpanel0.weighty = 1;
		gbcpanel0.anchor = GridBagConstraints.SOUTH;
		gbpanel0.setConstraints(scparea0, gbcpanel0);
		panel0.add(scparea0);

		panel1 = new JPanel();
		GridBagLayout gbpanel1 = new GridBagLayout();
		GridBagConstraints gbcpanel1 = new GridBagConstraints();
		panel1.setBorder(BorderFactory.createEmptyBorder(15,15,15,15));
		panel1.setLayout(gbpanel1);
		gbcpanel0.gridx = 1;
		gbcpanel0.gridy = 4;
		gbcpanel0.gridwidth = 18;
		gbcpanel0.gridheight = 18;
		gbcpanel0.fill = GridBagConstraints.BOTH;
		gbcpanel0.weightx = 1;
		gbcpanel0.weighty = 0;
		gbcpanel0.anchor = GridBagConstraints.CENTER;
		gbpanel0.setConstraints(panel1, gbcpanel0);
		panel0.add(panel1);
		
		ImageIcon icon = new ImageIcon("./resources/Ruta1.jpg");
		Image resize = icon.getImage();
		resize = resize.getScaledInstance(600, 600, java.awt.Image.SCALE_SMOOTH);
		image = new JLabel(new ImageIcon(resize));
		panel1.add(image);

		setDefaultCloseOperation(EXIT_ON_CLOSE);

		setContentPane(panel0);
		pack();
		setVisible(true);
	}

	public void setAgent(UserAgent userAgent) {
		// TODO Auto-generated method stub
		this.userAgent = userAgent;
	}
}
