// file: TripOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology;

import jade.content.onto.*;
import jade.content.schema.*;
import jade.util.leap.HashMap;
import jade.content.lang.Codec;
import jade.core.CaseInsensitiveString;

/** file: TripOntology.java
 * @author ontology bean generator
 * @version 2019/08/14, 01:17:04
 */
public class TripOntology extends jade.content.onto.Ontology  {
  //NAME
  public static final String ONTOLOGY_NAME = "Trip";
  // The singleton instance of this ontology
  private static ReflectiveIntrospector introspect = new ReflectiveIntrospector();
  private static Ontology theInstance = new TripOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String SENDTRIPS_TRIPS="trips";
    public static final String SENDTRIPS="SendTrips";
    public static final String RESERVE_SEAT="seat";
    public static final String RESERVE_CHOOSEDTRIP="choosedTrip";
    public static final String RESERVE="Reserve";
    public static final String TRIP_ROUTE="route";
    public static final String TRIP_ID="id";
    public static final String TRIP_SEATS="seats";
    public static final String TRIP_CAPACITY="Capacity";
    public static final String TRIP_DEPARTURETIME="departureTime";
    public static final String TRIP="Trip";
    public static final String SEAT_OCUPANT="ocupant";
    public static final String SEAT="Seat";

  /**
   * Constructor
  */
  private TripOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema seatSchema = new ConceptSchema(SEAT);
    add(seatSchema, ontology.Seat.class);
    ConceptSchema tripSchema = new ConceptSchema(TRIP);
    add(tripSchema, ontology.Trip.class);

    // adding AgentAction(s)
    AgentActionSchema reserveSchema = new AgentActionSchema(RESERVE);
    add(reserveSchema, ontology.Reserve.class);

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema sendTripsSchema = new PredicateSchema(SENDTRIPS);
    add(sendTripsSchema, ontology.SendTrips.class);


    // adding fields
    seatSchema.add(SEAT_OCUPANT, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    tripSchema.add(TRIP_DEPARTURETIME, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    tripSchema.add(TRIP_CAPACITY, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    tripSchema.add(TRIP_SEATS, seatSchema, 0, ObjectSchema.UNLIMITED);
    tripSchema.add(TRIP_ID, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    tripSchema.add(TRIP_ROUTE, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    reserveSchema.add(RESERVE_CHOOSEDTRIP, tripSchema, ObjectSchema.MANDATORY);
    reserveSchema.add(RESERVE_SEAT, seatSchema, ObjectSchema.MANDATORY);
    sendTripsSchema.add(SENDTRIPS_TRIPS, tripSchema, 1, ObjectSchema.UNLIMITED);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
  }
